// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Demo struct {
	Phone string `path:"Phone,optional" validate:"xPhone"` // 手机号
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}
