// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"greet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			// 使用路由组中间件
			[]rest.Middleware{serverCtx.GreetMiddleware1, serverCtx.GreetMiddleware2},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/from/:name",
					Handler: GreetHandler(serverCtx),
				},
			}...,
		),
	)
}
